site_name: "QVpnStatus"
site_description: "VPN Status tray icon for monitoring VPN connection"
site_url: "https://mikeramsey.gitlab.io/qvpnstatus"
repo_url: "https://gitlab.com/mikeramsey/qvpnstatus"
repo_name: "mikeramsey/qvpnstatus"
site_dir: "public"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Code Reference:
  - cli.py: reference/cli.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    watch:
    - src/main/python/qvpnstatus
- macros:
    module_name: docs/macros
